### ISSUE TITLE
Background job never run successfully on Google Pixel

### ISSUE THREAD

**Issue by henrytao-me** [cds-snc/covid-shield-mobile#594]
## Environment

- Google Pixel 1 
- Android 10 
- Debug build with js bundle in it. 

## Possible cause

Debug build might not be compatible to run in background for testing.

```
    private static void initializeFlipper(
        Context context, ReactInstanceManager reactInstanceManager) {
        if (BuildConfig.DEBUG) {
            try {
                /*
                    We use reflection here to pick up the class that initializes Flipper,
                    since Flipper library is not available in release mode
                */
                Class<?> aClass = Class.forName("app.covidshield.ReactNativeFlipper");
                aClass
                    .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
                    .invoke(null, context, reactInstanceManager);
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            }
        }
    }
```

```
2020-07-10 08:11:29.370 15687-15687/? W/System.err: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjsc.so result: 0
2020-07-10 08:11:29.370 15687-15687/? W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:825)
2020-07-10 08:11:29.370 15687-15687/? W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
2020-07-10 08:11:29.370 15687-15687/? W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:621)
2020-07-10 08:11:29.370 15687-15687/? W/System.err:     at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:122)
2020-07-10 08:11:29.370 15687-15687/? W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
2020-07-10 08:11:29.370 15687-15687/? W/System.err:     at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
2020-07-10 08:11:29.370 15687-15687/? W/System.err:     at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:766)
2020-07-10 08:11:29.371 15687-15687/? W/System.err:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:673)
2020-07-10 08:11:29.371 15687-15687/? W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:611)
2020-07-10 08:11:29.371 15687-15687/? W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:559)
2020-07-10 08:11:29.371 15687-15687/? W/System.err:     at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:297)
2020-07-10 08:11:29.371 15687-15687/? W/System.err:     at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:271)
2020-07-10 08:11:29.372 15687-15687/? W/System.err:     at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
2020-07-10 08:11:29.372 15687-15687/? W/System.err:     at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
2020-07-10 08:11:29.372 15687-15687/? W/System.err:     at app.covidshield.MainApplication.onCreate(MainApplication.java:75)
2020-07-10 08:11:29.372 15687-15687/? W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
2020-07-10 08:11:29.372 15687-15687/? W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
2020-07-10 08:11:29.372 15687-15687/? W/System.err:     at android.app.ActivityThread.access$1300(ActivityThread.java:219)
2020-07-10 08:11:29.372 15687-15687/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
2020-07-10 08:11:29.373 15687-15687/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-07-10 08:11:29.373 15687-15687/? W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-07-10 08:11:29.373 15687-15687/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-07-10 08:11:29.373 15687-15687/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-07-10 08:11:29.373 15687-15687/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-07-10 08:11:29.373 15687-15687/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-07-10 08:11:29.373 15687-15687/? E/SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: couldn't find DSO to load: libjsc.so result: 0 result: 0
```

## Suggestion

Try release build with Sentry log.

**Comment by henrytao-me** [comment]
Close as confirm background job runs as expected in production build. I was testing debug build before.
